name: Build and Push Release

on:
  workflow_dispatch:
    inputs:
      tagname:
        description: 'Tag name'
        required: true
        default: '0.0.0'

env:
  PUID: '1000'
  PGID: '1000'
  PHP_TZ: 'UTC'

jobs:
  multiarch:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - 
        name: Log in to the ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/dodancs/invoiceshelf-sk
          # generate Docker tags based on the following events/attributes
          tags: |
            type=sha
            testing-${{ github.run_id }}
            ${{ github.event.inputs.tagname }}
            latest
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          build-args: |
            TARGET=release
          push: true
          tags: ${{ steps.meta.outputs.tags }}

